export const types = {
  NONE: "NONE",
  LOGGING_SUCCESS: "LOGGING_SUCCESS",
  LOGGING_FAILURE: "LOGGING_FAILURE",
  LOGGING_OUT: "LOGGING_OUT",
  MODAL_ACTIVE: "MODAL_ACTIVE",
  MODAL_INACTIVE: "MODAL_INACTIVE",
};
